### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by terrytangyuan** [kleveross/ftlib#17]
We need to setup continuous integration to test code changes. I see that Caicloud turned on Travis CI so we could just reuse that. We can also reuse some CI setup from ElasticDL.

@zw0610 Could you ask infra team to activate Travis for this repo?

/kind feature

**Comment by ddysher** [comment]
Travis is activated for this repo.

**Comment by terrytangyuan** [comment]
CI is failing on this repo again. This is because Travis stopped triggering builds for PRs recently. Please look into whether Travis has been setup correctly. It was working earlier.

**Comment by terrytangyuan** [comment]
https://github.com/caicloud/ftlib/pull/74 fixes the CI failure but could you look into Travis setup? @ddysher @pendoragon @zw0610

**Comment by zw0610** [comment]
@bbbmj is looking into the issue.

**Comment by bbbmj** [comment]
> @bbbmj is looking into the issue.

It's fixed after a series of mystic operations...
